---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mydb
spec:
  serviceName: "mydb"
  replicas: 2
  selector:
    matchLabels:
      tier: db
  template:
    metadata:
      name: mydbtemp
      labels:
        tier: db

    spec:
      containers:
        - name: conttt
          image: nginx
          ports:
            - containerPort: 80

